name: Scrape Match Data

on:
  schedule:
    - cron: '0 12 * * *'  # Εκτέλεση καθημερινά στις 12:00 UTC
  workflow_dispatch:  # Επιτρέπει την εκκίνηση χειροκίνητα από το UI του GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest  # Εκτέλεση σε διακομιστή Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Κάνει checkout τον κώδικα του repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Χρησιμοποιεί την έκδοση Python 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Εγκαθιστά τις εξαρτήσεις που έβαλες στο requirements.txt

    - name: Run scraping script
      run: |
        python scrape_matches.py  # Εκτελεί το script σου
